name: test

on:
  push:
    branches: [ main ]
  schedule:
    - cron:  "*/2 * * * *"


jobs:
  job1:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: use action 1
        uses: ./.github/actions/action1/
      - name: use action 2
        uses: ./.github/actions/action2
      - name: test command
        run: "[[ `curl --write-out %{http_code} --silent --output /dev/null staging-env.playground-hublo.com` == 200 ]] && echo 'test status code - OK'"

