name: test

on:
  push:
    branches: [ main ]

jobs:
  job1:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: use action 1
        uses: ./.github/actions/action1/
      - name: use action 2
        uses: ./.github/actions/action2

